# Generated by Django 4.1.1 on 2022-09-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default=1, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
