# Generated by Django 5.0.6 on 2024-05-28 09:55

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0004_person1"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apiapp.person",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
