# Generated by Django 5.0.6 on 2024-06-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0005_superuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person1",
        ),
    ]
