# Generated by Django 5.0.6 on 2024-06-05 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0006_delete_person1"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("workdescription", models.TextField()),
                ("edit", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SuperUser",
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="person_permissions_set",
                related_query_name="person",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="personwork",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="apiapp.person",
            ),
        ),
    ]
