# Generated by Django 5.0.6 on 2024-06-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0008_alter_person_managers_alter_person_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="personwork",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
