# Generated by Django 5.0.6 on 2024-06-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0009_alter_person_id_alter_personwork_id"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_superuser",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="person",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_permissions_set",
                to="auth.permission",
            ),
        ),
    ]
