# Generated by Django 5.0.4 on 2024-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_alter_person_groups_alter_person_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personwork',
            name='edit',
        ),
        migrations.AlterField(
            model_name='personwork',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
